### ISSUE TITLE
truth value of a Series is ambiguous...

### ISSUE THREAD

**Issue by jcquarto** [benfred/bens-blog-code#5]
trying to work through your blog post

in the section "map each artist to a sparse vector of their users", I keep getting a "The truth value of a Series is ambiguous" error. Well, after a *long* calculation.

Specifically, this snippet of code:
      for artist, group in data.groupby('artist') 
seems to be the offending line

Might there be some library you're loading which may have missed getting mentioned in the blog? Or perhaps a Python 2 vs Python 3 issue?

**Comment by benfred** [comment]
Apparently I was using an old version of pandas, needed to change the csr_matrix creation code by swapping these lines  here 2745eef723d7d2dd016825bcb3b5fcdc45d40ca0
```
-                             csr_matrix((group['plays'],
+                             csr_matrix((array(group['plays']),
```

There was also a typo and another minor issue after upgrading numpy fixed there =(. sorry about that.

If you're just playing around, I'd suggest sampling down to fewer users (for instance something like```head -n 200000 usersha1-artmbid-artname-plays.tsv > small.tsv``` and then using that instead). This code takes approximately forever to run - performance wasn't a goal for this post.

**Comment by jcquarto** [comment]
thanks for fixing!

Yes, I wrote my own CSV file with just a handful of users and songs and plays, with a predefined overlap. Maybe 50 lines of code, way better than 500mb from last.fm :)

**Comment by benfred** [comment]
awesome! let me know how it goes.
