### ISSUE TITLE
what is filename in your code?

### ISSUE THREAD

**Issue by sagar-m** [benfred/bens-blog-code#7]
Hi, 

Thanks for the matrix factorization blog. I am trying to understand it. I should be starting with cleaning the last.fm files. When I run your code:

where do I define or point that "filename" in your code below is "usersha1-artmbid-artname-plays.tsv" ?
Seems like you are missing a couple of lines. on how to execute these functions.

class MusicData(object):
    def __init__(self, filename):
        # load TSV file from disk
        self.data = pandas.read_table(filename,
                                      usecols=[0, 2, 3],
                                      names=['user', 'artist', 'plays'])

Thank you so much.

Best regards,
Sagar

p.s. new to python. Also, I am not clear what you are doing here. thanks.

**Comment by benfred** [comment]
The filename is set here : https://github.com/benfred/bens-blog-code/blob/master/distance-metrics/generate_json.py#L163

Having said that, you really should use the example file in my implicit project: its much much faster than the code in this repository. I'll update the distance metrics post to point to it sometime soon
https://github.com/benfred/implicit/blob/master/examples/lastfm.py (it supports bm25/tfidf/cosine etc nearest neighbour distances in addition to the MF code).

**Comment by sagar-m** [comment]
Hi Ben,

Thank you very much for your note. I will check this out right now.

On a separate note, I am job-hunting as a data scientist in any location,
and was wondering if you are aware of any openings.

Highly appreciate it.

Best regards,
Sagar
